# Generated by Django 5.0.2 on 2024-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('language', models.CharField(max_length=2)),
                ('link', models.URLField()),
                ('pubdate', models.DateField()),
                ('updated', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('expire', models.DateField()),
                ('jobtype', models.CharField(max_length=50)),
            ],
        ),
    ]
