# Generated by Django 5.0.7 on 2024-07-22 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(default=None, max_length=100, null=True)),
                ('companyname', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('pincode', models.CharField(default=None, max_length=20, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default=None, max_length=30, null=True)),
                ('fblink', models.URLField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_data_policy_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_facebook_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_full_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_page_matching_approach',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='facebook_apply_data_callback_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='facebook_apply_data_custom_questions_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='facebook_apply_data_email_field_optional',
        ),
        migrations.RemoveField(
            model_name='job',
            name='facebook_apply_data_phone_number_field_optional',
        ),
        migrations.RemoveField(
            model_name='job',
            name='facebook_apply_data_work_experience_field_optional',
        ),
        migrations.RemoveField(
            model_name='job',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='job',
            name='basicpay',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='jobdesc',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='jobid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(default='Full_Time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(default='monthly', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.employer'),
        ),
    ]
